# Please insert new items alphabetically.

core-formats:
  members:
    - benilovj
    - binaryberry
    - dsingleton
    - boffbowsh
    - fofr
    - gpeng
    - tvararu
    - mgrassotti

  channel:
    "#core-formats"

  exclude_titles:
    - "[DO NOT MERGE]"
    - DO NOT MERGE
    - WIP

  quotes:
    - Everyone should have the opportunity to learn. Don’t be afraid to pick up stories on things you don’t understand and ask for help with them.
    - Keep making puns, and when you do make sure to @benilovj.
    - We focus on users - always starting with ‘why’ we are doing something, not ‘what’ we are doing.
    - If it’s gonna take more than 30 minutes, or it needs deploying - write a card for it and chat to Jen.
    - Try to pair when possible.
    - Pick up work from the 'ready column' - don't cherry pick from the backlog/ice box or ‘next’ column.
    - Any excuse for cake - or generally celebrating awesomeness
    - Never be afraid to suggest better ways of working.
    - Be nice and respect each other. Support each other.
    - Don’t be a silo of knowledge
    - Ask if anyone needs support before picking up new work
    - Be considerate to remote workers
    - Avoid gendered language when it isn’t needed
    - Turn up to meetings on time, one person speaks at a time
    - Stories should start with a user need
    - It’s not done until it’s in the hands of the people who need it
    - When working at home, dial in to stand-up
    - Keep things up-to-date - like the digital wall, team calendar
    - Communicate what you’re working on - make sure you don’t leave people out of the loop
    - Trello should reflect what everyone’s working on - if it's going to take longer than 30 minutes or it's going to need to be deployed - write a card and chat with Jen.
    - Meetings must have a clear purpose and make the best use of everyone’s time
    - Keep our desks and work spaces tidy (including the tea stand)
    - Get involved with user research - everyone should spend 2 hours every 6 weeks learning about our users

specialist-publisher:
  members:
    - mathildathompson
    - Rosa-Fox
    - christopherwong

  channel:
    "#specialist-publisher"

custom:
  members:
    - brenetic
    - davidbasalla
    - h-lame
    - issyl0
    - jennyd
    - sihugh

  channel:
    "#custom"

  exclude_titles:
    - "[DO NOT MERGE]"
    - DO NOT MERGE
    - WIP

finding-things:
  members:
    - bishboria
    - Davidslv
    - jackscotti
    - MatMoore
    - mobaig
    - rboulton
    - tijmenb

  channel:
    "#finding-things"

  exclude_titles:
    - "[DO NOT MERGE]"
    - DO NOT MERGE
    - WIP

testing:
  members:
    - benilovj
    - binaryberry
    - boffbowsh
    - fofr
    - jamiecobbett

  channel:
    "#testing"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

  quotes:
    - Everyone should have the opportunity to learn. Don’t be afraid to pick up stories on things you don’t understand and ask for help with them.
    - Be nice and respect each other. Support each other.
    - Don’t be a silo of knowledge

tea:
  members:
    - binaryberry

  channel:
    "#tea"

  quotes:
    - "Gentle reminder to please empty the milk jug before the weekend! :rainbow:"
    - "Time to be a tea-m player and take out the milk before the weekend! :facepalm:"
    - "Good news, the weekend is starting. Bad news, YOU have to throw out the milk first."
    - "We want YOU to empty the milk jug! http://georgiamidwife.org/wp-content/uploads/2015/07/We-want-you-image.png"
    - "Let's avoid Monday cheese, and empty the milk jug now. :cheese:"
    - "Hello beau-teas! Time to empty the milk jug, and go for a :beer:!"
    - "Reminder of your du-tea to empty the milk jug before the weekend. Thank you!"

publishing-platform:
  members:
    - danielroseman
    - elliotcm
    - steventux
    - dougdroper
    - tuzz

  channel:
    "#publishing-platform"

  quotes:
    - "If you're not well, don't come in to the office."
    - "Pair where possible."
    - "Seek to share knowledge inside and outside of the team."
    - "Before starting new work, see if others can be helped with their existing work."
    - "Document all decisions and make sure they're shared."
    - "Read your email regularly."
    - "Meetings are expensive, make sure you get value out of them."
    - "Be open to questioning, challenges and discussion (and do it respectfully and with empathy)."
    - ":eggplant:"
    - "http://s18.postimg.org/ryk1eup09/automotivator.jpg"

govuk-infrastructure:
  members:
    - alexmuller
    - deanwilson
    - mattbostock
    - rjw1
    - surminus

  channel:
    "#govuk-infrastructure"

  quotes:
    - "If you're not well, don't come in to the office."
    - "Pair where possible."
    - "Seek to share knowledge inside and outside of the team."
    - "Before starting new work, see if others can be helped with their existing work."
    - "Document all decisions and make sure they're shared."
    - "Read your email regularly."
    - "Meetings are expensive, make sure you get value out of them."
    - "Be open to questioning, challenges and discussion (and do it respectfully and with empathy)."
    - ":eggplant:"
    - "http://s18.postimg.org/ryk1eup09/automotivator.jpg"

service-manual:
  members:
    - AndrewVos
    - thehenster
    - gemmaleigh

  channel:
    "#servicemanual"

  quotes:
    - "hi"
