# Please insert new items alphabetically.

content-tools:
  members:
    - alecgibson
    - andrewgarner
    - chao-xian
    - kylemacpherson
    - pmanrubia
    - mgrassotti
    - theKHutDeveloper

  channel:
    "#content-tools"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - "Waiting on factcheck"
    - WIP

  use_labels: true

  exclude_labels:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - "Waiting on factcheck"

  quotes:
    - If it’s gonna take more than 30 minutes, or it needs deploying - write a card for it and chat to the Product Manager.
    - Try to pair when possible.
    - Be considerate to remote workers and follow the Working from home practices https://gov-uk.atlassian.net/wiki/x/Bz_5Bw and https://gov-uk.atlassian.net/wiki/display/CT/Working+from+home+ideas
    - Who's organising the next team lunch?
    - If you're not well, don't come in to the office. And get some rest!
    - Set your Slack status to away or do not disturb so people know whether they can disturb you.
    - Has your story got points?
    - Don't forget to assign your face to a card and PR if you're working on it or reviewing.
    - Don't forget the Jabra and fisheye lens if you're dialing in people!
    - If Hangouts is being flaky, try Slack calls or appear.in!
    - I AM VENGEANCE! I AM THE NIGHT! I AM BATMAN! :batsignal:

design-system:
  members:
    - 36degrees
    - alex-ju
    - dashouse
    - hannalaakso
    - igloosi
    - nickcolley
    - timpaul

  channel:
    "#govuk-design-system"

  exclude_titles:
    - DO NOT MERGE
    - WIP

email:
  members:
    - 1pretz1
    - bevanloon
    - gpeng
    - kevindew
    - rubenarakelyan
    - thomasleese

  channel:
    "#email"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[WIP]"

frontend-design:
  members:
    - vanitabarrett
    - maxgds
    - miaallers
    - alextea
    - steventux
    - emmabeynon
    - leenagupte
    - fmlharrison

  channel:
    "#frontend-design"

  exclude_titles:
    - "DO NOT MERGE"
    - "WIP"
    - "REVIEW ONLY"

modelling-services:
  members:
    - Davidslv
    - deborahchua
    - sihugh
    - andysellick

  channel:
    "#modelling-services"

  exclude_titles:
    - "[DO NOT MERGE]"
    - DO NOT MERGE
    - WIP

  quotes:
    - I'm pretty sure there's a lot more to life than being really, really, ridiculously good looking. And I plan on finding out what that is.
    - Where shall we go for lunch?
    - Where's the data?

taxonomy:
  members:
    - cbaines
    - koetsier
    - davidbasalla
    - tomsabin

  channel:
    "#taxonomy"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - WIP
    - "[REVIEW ONLY]"
    - REVIEW ONLY
    - "[SEAL IGNORE]"
    - RFC

start-pages:
  members:
    - emmabeynon
    - leenagupte

  channel:
    "#start-pages"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - WIP
    - [WIP]

testing:
  members:
    - binaryberry
    - boffbowsh
    - fofr

  channel:
    "#testing"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

  quotes:
    - Everyone should have the opportunity to learn. Don’t be afraid to pick up stories on things you don’t understand and ask for help with them.
    - Be nice and respect each other. Support each other.
    - Don’t be a silo of knowledge

reliability-engineering:
  members:
    - deanwilson
    - surminus
    - afda16
    - issyl0
    - stephenharker

  channel:
    "#r20g-infra-internal"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

  quotes:
    - "Someone needs to think of some new quotes!"

# servicemanual:
#   members:
#
#   channel:
#     "#servicemanual"
#
#   exclude_titles:
#     - DO NOT MERGE
#     - WIP

publishing-frontend:
  members:
    - miaallers
    - andysellick
    - vanitabarrett
    - fofr

  channel:
    "#publishing-frontend"

  exclude_titles:
    - "[DO NOT MERGE]"

govuk-madetech:
  members:
    - app/dependabot
    - chrisblackburn
    - danielburnley
    - davidwinter
    - idabmat
    - lukemorton
    - naliwajek
    - RoryMacDonald
    - RyanMacG
    - adrianclay
    - SebAshton

  channel:
    "#govuk-madetech"

# The objective with Start pages, Frontend navigation & Modelling services
govuk-easier-finding:
  members:
    - alextea
    - andysellick
    - Davidslv
    - deborahchua
    - emmabeynon
    - fofr
    - leenagupte
    - maxgds
    - miaallers
    - sihugh
    - steventux
    - tijmenb
    - vanitabarrett

  channel:
    "#govuk-easier-finding"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "WIP"

platform_support:
  members:
    - boffbowsh
    - dwhenry
    - elenatanasoiu
    - h-lame
    - suzannehamilton

  channel:
    "#platform_support"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "WIP"
