# Please insert new items alphabetically.
design-system-dev:
  members:
    - 36degrees
    - dashouse
    - hannalaakso
    - igloosi
    - nickcolley
    - timpaul

  channel:
    "#design-system-dev"

  exclude_titles:
    - DO NOT MERGE
    - WIP

govuk-pub-workflow:
  members:
    - 1pretz1
    - alex-ju
    - benthorner
    - DilwoarH
    - emmabeynon
    - erino
    - kevindew
    - kgarwood
    - leenagupte
    - MuriloDalRi
    - tijmenb

  channel:
    "#govuk-pub-workflow"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - "DON'T MERGE"
    - "DO NOT MERGE"
    - "WIP"

govuk-data-informed:
  members:
    - chao-xian
    - cbaines
    - kylemacpherson
    - maxgds
    - peteglondon
    - pmanrubia

  channel:
    "#govuk-data-informed"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - WIP

  use_labels: true

  exclude_labels:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE

  quotes:
    - Be the change you want to see!
    - Be Excellent To Each Other!
    - Be considerate to remote workers. Ask \#remote-workers for tips.
    - If you're not well, don't come in to the office. And get some rest!
    - I AM VENGEANCE! I AM THE NIGHT! I AM BATMAN! :batsignal:

govuk-licensing:
  members:
    - PeteLeaman
    - SomniGiggles
    - steven-radford
    - chrispapto

  channel:
    "#govuk-licensing"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[WIP]"

govuk-platform-health:
  members:
    - AlanGabbianelli
    - andreagrandi
    - barrucadu
    - bevanloon
    - binaryberry
    - brucebolt
    - deborahchua
    - elliotcm
    - hongoose
    - rubenarakelyan
    - steventux
    - thomasleese

  channel:
    "#govuk-platform-health"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "WIP"

  quotes:
    - Continue getting involved in Hong's weird team activities
    - If a fika isn't happening, start it
    - Fika is a work-free environment
    - We encourage you to do Fika everyday - don't be shy about initiating it
    - Team lunch anyone?
    - Listen to each other's points of view
    - Spot opportunities, be brave in announcing them
    - Ask for more clarity if needed
    - Feel free to ask for help/questions/etc
    - Try pairing, as well as not pairing...both are good
    - Ask questions when you don't know something - it will also give others the confidence to ask their questions
    - It's OK to not know how something works
    - Be supportive - knowledge sharing helps the team achieve its goals
    - Don't rush on to the next thing, pause, help out, deliver work as a team
    - Work at a considered / sustainable pace
    - Take responsibility for your work until it's deployed
    - "Awareness of everyone's preferences on ways of working (more info: https://drive.google.com/drive/folders/1qllr2HfwGg6JL1VCWPCQusMokYYCq_-Z)"
    - Support remote working as the norm
    - If you're sick, stay home
    - If not well enough to work, don't, even from home
    - Slack as primary point of contact (email for long form stuff)
    - "[Get ready to form] sub teams on larger pieces of work"
    - When an epic emerges, write all the cards so we can _share the work_

  compact: true

re-infra-internal:
  members:
    - afda16
    - deanwilson
    - dougneal
    - issyl0
    - rtrinque
    - schmie
    - stephenharker

  channel:
    "#re-infra-internal"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

  quotes:
    - "Someone needs to think of some new quotes!"

  compact: true

re-observe:
  members:
    - DavidJeche
    - ejrowley
    - idavidmcdonald
    - kentsanggds
    - philandstuff

  channel:
    "#re-observe"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

bot-testing:
  members:
    - binaryberry

  channel:
    "#bot-testing"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

  quotes:
    - Everyone should have the opportunity to learn. Don’t be afraid to pick up stories on things you don’t understand and ask for help with them.
    - Be nice and respect each other. Support each other.
    - Don’t be a silo of knowledge
