# Please insert new items alphabetically.

core-formats:
  members:
    - benilovj
    - benlovell
    - binaryberry
    - boffbowsh
    - fofr
    - jamiecobbett

  repos:
    - Accessible-Media-Player
    - asset-manager
    - content-register
    - content-store
    - external-link-tracker
    - feedback
    - frontend
    - gds_zendesk
    - government-frontend
    - govuk_admin_template
    - govuk_content_api
    - govuk-content-schemas
    - govuk_content_models
    - info-frontend
    - maslow
    - metadata-api
    - panopticon
    - publisher
    - release
    - router-api
    - short-url-manager
    - signonotron2
    - specialist-frontend
    - specialist-publisher
    - static
    - support
    - support-api
    - travel-advice-publisher
    - url-arbiter
    - whitehall

  channel:
    "#core-formats"

  exclude_titles:
    - "[DO NOT MERGE]"
    - DO NOT MERGE
    - WIP

custom:
  members:
    - dsingleton
    - issyl0
    - jennyd
    - marksheldonGDS
    - mikejustdoit
    - tommyp
    - h-lame
    - davidbasalla

  repos:
    - business-support-api
    - calendars
    - contacts-admin
    - contacts-frontend
    - content-register
    - content-store
    - courts-api
    - courts-frontend
    - govuk-content-schemas
    - hmrc-manuals-api
    - imminence
    - licence-finder
    - manuals-frontend
    - mapit
    - optic14n
    - pre-transition-stats
    - publishing-api
    - side-by-side-browser
    - smart-answers
    - specialist-publisher
    - static
    - trade-tariff-admin
    - trade-tariff-backend
    - trade-tariff-frontend
    - transition
    - transition-config
    - transition-stats
    - url-arbiter
    - whitehall

  channel:
    "#custom"

  exclude_titles:
    - "[DO NOT MERGE]"
    - DO NOT MERGE
    - WIP

finding-things:
  members:
    - alext
    - alextea
    - bishboria
    - jackscotti
    - mobaig
    - rboulton
    - stephen-richards
    - tijmenb
    
  repos:
    - Accessible-Media-Player
    - ansible-graphite
    - ansible-playbook-docker_server
    - ansible-playbook-gandalf
    - ansible-playbook-hipache
    - ansible-playbook-redis
    - ansible-playbook-tsuru_api
    - ansible-role-openconnect
    - ansible-statsd
    - assets-directgov
    - authenticating-proxy
    - backdrop-transactions-explorer-collector
    - business-support-finder
    - cdn-acceptance-tests
    - ci-puppet
    - cloudflare-configure
    - collections
    - collections-publisher
    - content-store
    - design-principles
    - digitalmarketplace-utils
    - document-kit
    - e-petitions
    - email-alert-api
    - email-alert-monitor
    - example-java-jetty
    - fabric-scripts
    - finder-frontend
    - fourth-wall
    - frontend
    - gds-boxen
    - github_sshkey_checker
    - govdelivery-email-templates
    - government-service-design-manual
    - govuk_content_api
    - govuk_content_models
    - govuk_elements
    - govuk_frontend_toolkit
    - govuk_frontend_toolkit_gem
    - govuk_frontend_toolkit_npm
    - govuk_message_queue_consumer
    - govuk_migration_plan_public
    - govuk_mirror-puppet
    - govuk_prototype_kit
    - govuk_template
    - govuk-content-best-practices
    - govuk-content-schema-test-helpers
    - govuk-content-schemas
    - govuk-lint
    - govuk-rails-app-template
    - gradle-gatling-plugin
    - ier-frontend
    - interaction-diagrams
    - maslow
    - metadata-api
    - multicloud-deploy
    - packager
    - panopticon
    - payment-prototype-options
    - policy-publisher
    - prototyping
    - publishing-api
    - puppet-autofsck
    - puppet-rcs
    - recommended-links
    - release
    - router
    - rummager
    - search-admin
    - search-performance-dashboard
    - signonotron2
    - situation-room
    - situation-room-dashboard
    - slimmer
    - smart-answers
    - smartdown
    - smokey
    - specialist-publisher
    - static
    - styleguides
    - support
    - support-api
    - terraform
    - trade-tariff-admin
    - trade-tariff-backend
    - transformation-dashboard
    - transition-config
    - transition-stats
    - tsuru-ansible
    - tsuru-dashboard
    - tsuru-terraform
    - tsuru-testing
    - whitehall

  channel:
    "#finding-things"

  exclude_titles:
    - "[DO NOT MERGE]"
    - DO NOT MERGE
    - WIP

testing:
  members:
    - ajlanghorn
    - benilovj
    - binaryberry
    - boffbowsh
    - fofr
    - jamiecobbett

  repos:
    - Accessible-Media-Player
    - asset-manager
    - content-register
    - content-store
    - external-link-tracker
    - feedback
    - frontend
    - government-frontend
    - govuk_content_api
    - govuk-content-schemas
    - info-frontend
    - maslow
    - metadata-api
    - panopticon
    - publisher
    - release
    - short-url-manager
    - signonotron2
    - specialist-frontend
    - specialist-publisher
    - static
    - support
    - support-api
    - travel-advice-publisher
    - url-arbiter
    - whitehall

  channel:
    "#testing"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP
