# Please insert new items alphabetically.
govuk-datagovuk-tech:
  members:
    - andrewgarner
    - benthorner
    - emmabeynon
    - hannako
    - laurentqro
    - maxgds
    - rossjones

  channel:
    "#govuk-datagovuk-tech"

  exclude_titles:
    - "WIP"
    - "[WIP]"
    - "DO NOT MERGE"
    - "[DO NOT MERGE]"

  include_repos:
    - datagovuk_publish
    - datagovuk_find
    - datagovuk_infrastructure

govuk-data-informed:
  members:
    - chao-xian
    - kylemacpherson
    - matmoore
    - pmanrubia
    - theKHutDeveloper
    - tombye

  channel:
    "#govuk-data-informed"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - "Waiting on factcheck"
    - WIP

  use_labels: true

  exclude_labels:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - "Waiting on factcheck"

  quotes:
    - Be the change you want to see!
    - Help each other out. Pair if possible.
    - Be considerate to remote workers. Ask \#remote-workers for tips.
    - Who's organising the next team lunch?
    - If you're not well, don't come in to the office. And get some rest!
    - Does your work have a story? Has your story got points?
    - I AM VENGEANCE! I AM THE NIGHT! I AM BATMAN! :batsignal:

design-system-dev:
  members:
    - 36degrees
    - alex-ju
    - dashouse
    - hannalaakso
    - igloosi
    - nickcolley
    - timpaul

  channel:
    "#design-system-dev"

  exclude_titles:
    - DO NOT MERGE
    - WIP

govuk-porg-pages:
  members:
    - andysellick
    - Davidslv
    - MahmudH
    - rubenarakelyan
    - sihugh
    - tijmenb

  channel:
    "#govuk-porg-pages"

  exclude_titles:
    - WIP
    - "[WIP]"
    - "[DO NOT MERGE]"

  quotes:
    - I find your lack of an easily implemented change process for organisations disturbing
    - When 900 years you have worked on Whitehall, look as good you will not.
    - These are not the organisation pages you are looking for
    - Migration is the path to the dark side. Migration leads to anger; anger leads to hate; hate leads to suffering. I sense much migration in you.

govuk-platform-health:
  members:
    - barrucadu
    - bevanloon
    - deborahchua
    - elliotcm
    - hongoose
    - kevindew
    - steventux
    - thomasleese

  channel:
    "#govuk-platform-health"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "WIP"

r20g-infra-internal:
  members:
    - afda16
    - issyl0
    - jljalderman
    - rtrinque
    - stephenharker
    - surminus
    - suthagahrt

  channel:
    "#r20g-infra-internal"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

  quotes:
    - "Someone needs to think of some new quotes!"

govuk-tax-and-nav:
  members:
    - 1pretz1
    - alextea
    - cbaines
    - koetsier
    - leenagupte
    - miaallers
    - mmholland88
    - myst3ria
    - peteglondon
    - tijmenb
    - vanitabarrett

  channel:
    "#govuk-tax-and-nav"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - WIP
    - "[SEAL IGNORE]"
    - RFC

testing:
  members:
    - binaryberry
    - boffbowsh
    - fofr

  channel:
    "#bot-testing"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

  quotes:
    - Everyone should have the opportunity to learn. Don’t be afraid to pick up stories on things you don’t understand and ask for help with them.
    - Be nice and respect each other. Support each other.
    - Don’t be a silo of knowledge

govuk-licensing:
  members:
    - PeteLeaman
    - SomniGiggles
    - steven-radford
    - chrispapto

  channel:
    "#govuk-licensing"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[WIP]"
