core-formats:
  members:
    - binaryberry
    - jamiecobbett
    - boffbowsh
    - benilovj
    - fofr
    - edds

  repos:
    - maslow
    - signonotron2
    - short-url-manager
    - support
    - feedback
    - frontend
    - specialist-publisher
    - publisher
    - whitehall
    - govuk_content_api
    - release
    - metadata-api
    - travel-advice-publisher
    - info-frontend
    - government-frontend
    - support-api
    - external-link-tracker
    - specialist-frontend
    - static
    - asset-manager
    - content-store
    - url-arbiter
    - content-register
    - panopticon
    - govuk-content-schemas
    - Accessible-Media-Player

  channel:
    "#core-formats"

custom:
  members:
    - jennyd
    - dsingleton
    - tommyp
    - issyl0
    - mikejustdoit
    - marksheldonGDS

  repos:
    - business-support-api
    - calendars
    - contacts-admin
    - contacts-frontend
    - content-register
    - content-store
    - courts-api
    - courts-frontend
    - govuk-content-schemas
    - hmrc-manuals-api
    - imminence
    - licence-finder
    - manuals-frontend
    - mapit
    - optic14n
    - pre-transition-stats
    - publishing-api
    - side-by-side-browser
    - smart-answers
    - specialist-publisher
    - static
    - trade-tariff-admin
    - trade-tariff-backend
    - trade-tariff-frontend
    - transition
    - transition-config
    - transition-stats
    - url-arbiter
    - whitehall

  channel:
    "#custom"

finding-things:
  members:
    - alext
    - alextea
    - bishboria
    - KushalP
    - markhurrell
    - rboulton
    - tijmenb
    - jackscotti

  repos:
    - static
    - slimmer
    - panopticon
    - frontend
    - whitehall
    - smart-answers
    - rummager
    - smokey
    - design-principles
    - signonotron2
    - prototyping
    - govuk_content_models
    - trade-tariff-backend
    - styleguides
    - e-petitions
    - govuk_content_api
    - business-support-finder
    - govuk_frontend_toolkit
    - support
    - fabric-scripts
    - assets-directgov
    - government-service-design-manual
    - transition-config
    - release
    - Accessible-Media-Player
    - gds-boxen
    - govuk_frontend_toolkit_gem
    - trade-tariff-admin
    - packager
    - transition-stats
    - ci-puppet
    - transformation-dashboard
    - govuk_template
    - govuk_mirror-puppet
    - fourth-wall
    - maslow
    - router
    - govuk_frontend_toolkit_npm
    - finder-frontend
    - specialist-publisher
    - backdrop-transactions-explorer-collector
    - search-performance-dashboard
    - govuk_elements
    - govuk_migration_plan_public
    - collections
    - search-admin
    - cdn-acceptance-tests
    - smartdown
    - support-api
    - govuk_prototype_kit
    - collections-publisher
    - gradle-gatling-plugin
    - metadata-api
    - email-alert-api
    - cloudflare-configure
    - govuk-content-schemas
    - email-alert-monitor
    - policy-publisher
    - govdelivery-email-templates
    - ier-frontend
    - govuk-content-schema-test-helpers
    - interaction-diagrams
    - tsuru-ansible
    - tsuru-terraform
    - payment-prototype-options
    - digitalmarketplace-utils
    - govuk-content-best-practices
    - multicloud-deploy
    - ansible-role-openconnect
    - ansible-playbook-docker_server
    - ansible-playbook-gandalf
    - ansible-playbook-hipache
    - ansible-playbook-tsuru_api
    - ansible-playbook-redis
    - terraform
    - github_sshkey_checker
    - authenticating-proxy
    - puppet-rcs
    - puppet-autofsck
    - tsuru-dashboard
    - govuk-rails-app-template
    - ansible-statsd
    - ansible-graphite
    - tsuru-testing
    - document-kit
    - example-java-jetty
    - govuk-lint
    - situation-room
    - situation-room-dashboard

  channel:
    "#finding-things"

testing:
  members:
    - binaryberry
    - jamiecobbett
    - boffbowsh
    - benilovj
    - fofr
    - edds

  repos:
    - maslow
    - signonotron2
    - short-url-manager
    - support
    - feedback
    - frontend
    - specialist-publisher
    - publisher
    - whitehall
    - govuk_content_api
    - release
    - metadata-api
    - travel-advice-publisher
    - info-frontend
    - government-frontend
    - support-api
    - external-link-tracker
    - specialist-frontend
    - static
    - asset-manager
    - content-store
    - url-arbiter
    - content-register
    - panopticon
    - govuk-content-schemas
    - Accessible-Media-Player

  channel:
    "#testing"
