# Please insert new items alphabetically.

core-formats:
  members:
    - steventux
    - boffbowsh
    - fofr
    - gpeng
    - mgrassotti
    - Rosa-Fox
    - andrewgarner
    - bevanloon
    - tvararu

  channel:
    "#core-formats"

  exclude_titles:
    - "[DO NOT MERGE]"
    - DO NOT MERGE
    - WIP
    - "[DO NOT SEAL]"
    - "[DON'T SEAL]"
    - DO NOT SEAL
    - DON'T SEAL

  quotes:
    - Everyone should have the opportunity to learn. Don’t be afraid to pick up stories on things you don’t understand and ask for help with them.
    - We focus on users - always starting with ‘why’ we are doing something, not ‘what’ we are doing.
    - If it’s gonna take more than 30 minutes, or it needs deploying - write a card for it and chat to Shilpa.
    - Try to pair when possible.
    - Pick up work from the 'ready column' - don't cherry pick from the backlog/ice box or ‘next’ column.
    - Any excuse for cake - or generally celebrating awesomeness
    - Never be afraid to suggest better ways of working.
    - Be nice and respect each other. Support each other.
    - Don’t be a silo of knowledge
    - Ask if anyone needs support before picking up new work
    - Be considerate to remote workers
    - Avoid gendered language when it isn’t needed
    - Turn up to meetings on time, one person speaks at a time
    - Stories should start with a user need
    - It’s not done until it’s in the hands of the people who need it
    - When working at home, dial in to stand-up
    - Keep things up-to-date - like the digital wall, team calendar
    - Communicate what you’re working on - make sure you don’t leave people out of the loop
    - Trello should reflect what everyone’s working on - if it's going to take longer than 30 minutes or it's going to need to be deployed - write a card and chat with Jen.
    - Meetings must have a clear purpose and make the best use of everyone’s time
    - Keep our desks and work spaces tidy (including the tea stand)
    - Get involved with user research - everyone should spend 2 hours every 6 weeks learning about our users

mainstream-pop-up:
  members:
    - binaryberry
    - issyl0
    - cbaines

  channel:
    "#mainstream-pop-up"

custom:
  members:
    - brenetic
    - davidbasalla
    - deborahchua
    - emmabeynon
    - sihugh
    - whoojemaflip

  channel:
    "#custom"

  exclude_titles:
    - "[DO NOT MERGE]"
    - DO NOT MERGE
    - WIP

finding-things:
  members:
    - alextea
    - carolinegreen
    - carvil
    - Davidslv
    - klssmith
    - MatMoore
    - mobaig
    - rubenarakelyan
    - tijmenb
    - suzannehamilton

  channel:
    "#finding-things"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - WIP

email:
  members:
    - jennyd

  channel:
    "#email"

testing:
  members:
    - binaryberry
    - boffbowsh
    - fofr

  channel:
    "#testing"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

  quotes:
    - Everyone should have the opportunity to learn. Don’t be afraid to pick up stories on things you don’t understand and ask for help with them.
    - Be nice and respect each other. Support each other.
    - Don’t be a silo of knowledge

tea:
  members:
    - binaryberry

  channel:
    "#tea"

  quotes:
    - "Tea ready at Corestum :rainbow:"
    - "Tea ready at Corestum. Bon appé-tea! :baguette:"
    - "Tea ready at Corestum. :tea:"
    - "Tea ready at Corestum. :teapot:"
    - "Tea ready at Corestum. :runner:"
    - "Tea ready at Corestum. :postal_horn:"
    - "Tea ready at Corestum. :confetti_ball:"
    - "Tea ready at Corestum. :tada:"
    - "Tea ready at Corestum. :gift:"
    - "Tea ready at Corestum. :gift_heart:"
    - "Tea ready at Corestum. :ribbon:"
    - "Tea ready at Corestum. :hotsprings:"
    - "Tea ready at Corestum. :corestum:"
    - "Tea ready at Corestum. :happyseal:"
    - "Tea ready at Corestum. :civilservant:"
    - "Tea ready at Corestum. :govuk:"
    - "Tea ready at Corestum. :informative_seal:"
    - "Tea ready at Corestum. :nyan_cat:"
    - "Tea ready at Corestum. :satisfied_seal:"
    - "Tea ready at Corestum. :pikachu:"
    - "Tea ready at Corestum. :shipit:"
    - "Tea ready at Corestum. :ship:"

publishing-platform:
  members:
    - danielroseman
    - kevindew
    - carlosmartinez
    - dougdroper
    - thomasleese

  channel:
    "#publishing-platform"

  quotes:
    - "If you're not well, don't come in to the office."
    - "Pair where possible."
    - "Seek to share knowledge inside and outside of the team."
    - "Before starting new work, see if others can be helped with their existing work."
    - "Document all decisions and make sure they're shared."
    - "Read your email regularly."
    - "Meetings are expensive, make sure you get value out of them."
    - "Be open to questioning, challenges and discussion (and do it respectfully and with empathy)."
    - ":eggplant:"
    - "http://s18.postimg.org/ryk1eup09/automotivator.jpg"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

govuk-infrastructure:
  members:
    - alexmuller
    - deanwilson
    - jonauman
    - rjw1
    - surminus
    - djsd123
    - dazahern

  channel:
    "#govuk-infrastructure"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

  quotes:
    - ":eggplant:"
    - "indeed"
    - "naming is hard"
    - "If it's Wednesday, go to Beck's"
    - "We :heart: Taylor Swift"

servicemanual:
  members:
    - thehenster
    - 36degrees

  channel:
    "#servicemanual"

  exclude_titles:
    - "[DO NOT MERGE]"
    - DO NOT MERGE
    - WIP

  exclude_repos:
    - govuk_elements
    - govuk_frontend_toolkit

  quotes:
    - ":wave:"

templateconsolidation:
  members:
    - nickcolley
    - miaallers
    - markhurrell

  channel:
    "#templateconsolidation"
