# Please insert new items alphabetically.

data-informed-content:
  members:
    - andrewgarner
    - chao-xian
    - kylemacpherson
    - pmanrubia
    - theKHutDeveloper
    - matmoore
    - peteglondon

  channel:
    "#data-informed-content"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - "Waiting on factcheck"
    - WIP

  use_labels: true

  exclude_labels:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - "Waiting on factcheck"

  quotes:
    - Be the change you want to see!
    - Help each other out. Pair if possible.
    - Be considerate to remote workers. Ask \#remote-workers for tips.
    - Who's organising the next team lunch?
    - If you're not well, don't come in to the office. And get some rest!
    - Does your work have a story? Has your story got points?
    - I AM VENGEANCE! I AM THE NIGHT! I AM BATMAN! :batsignal:

email:
  members:
    - 1pretz1
    - bevanloon
    - gpeng
    - kevindew
    - rubenarakelyan
    - thomasleese

  channel:
    "#email"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[WIP]"

frontend-design:
  members:
    - vanitabarrett
    - maxgds
    - miaallers
    - alextea
    - steventux
    - emmabeynon
    - leenagupte
    - fmlharrison

  channel:
    "#frontend-design"

  exclude_titles:
    - "DO NOT MERGE"
    - "WIP"
    - "REVIEW ONLY"

govuk-design-system:
  members:
    - 36degrees
    - alex-ju
    - dashouse
    - hannalaakso
    - igloosi
    - nickcolley
    - timpaul

  channel:
    "#govuk-design-system"

  exclude_titles:
    - DO NOT MERGE
    - WIP

# The objective with Start pages, Frontend navigation & Modelling services
govuk-easier-finding:
  members:
    - alextea
    - andysellick
    - Davidslv
    - deborahchua
    - emmabeynon
    - fofr
    - leenagupte
    - maxgds
    - miaallers
    - sihugh
    - steventux
    - tijmenb
    - vanitabarrett

  channel:
    "#govuk-easier-finding"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "WIP"

govuk-madetech:
  members:
    - app/dependabot
    - chrisblackburn
    - danielburnley
    - davidwinter
    - idabmat
    - lukemorton
    - naliwajek
    - RoryMacDonald
    - RyanMacG
    - adrianclay
    - SebAshton

  channel:
    "#govuk-madetech"

modelling-services:
  members:
    - Davidslv
    - deborahchua
    - sihugh
    - andysellick

  channel:
    "#modelling-services"

  exclude_titles:
    - "[DO NOT MERGE]"
    - DO NOT MERGE
    - WIP

  quotes:
    - I'm pretty sure there's a lot more to life than being really, really, ridiculously good looking. And I plan on finding out what that is.
    - Where shall we go for lunch?
    - Where's the data?

platform_support:
  members:
    - boffbowsh
    - dwhenry
    - elenatanasoiu
    - h-lame
    - suzannehamilton

  channel:
    "#platform_support"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "WIP"

publishing-frontend:
  members:
    - miaallers
    - andysellick
    - vanitabarrett
    - fofr

  channel:
    "#publishing-frontend"

  exclude_titles:
    - "[DO NOT MERGE]"

reliability-engineering:
  members:
    - afda16
    - deanwilson
    - issyl0
    - jljalderman
    - stephenharker
    - surminus
    - suthagahrt

  channel:
    "#r20g-infra-internal"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

  quotes:
    - "Someone needs to think of some new quotes!"

taxonomy:
  members:
    - cbaines
    - koetsier
    - davidbasalla
    - tomsabin

  channel:
    "#taxonomy"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - WIP
    - "[REVIEW ONLY]"
    - REVIEW ONLY
    - "[SEAL IGNORE]"
    - RFC

testing:
  members:
    - binaryberry
    - boffbowsh
    - fofr

  channel:
    "#bot-testing"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

  quotes:
    - Everyone should have the opportunity to learn. Don’t be afraid to pick up stories on things you don’t understand and ask for help with them.
    - Be nice and respect each other. Support each other.
    - Don’t be a silo of knowledge
