# Please insert new items alphabetically.

benchmarking:
  members:
    - Davidslv
    - deborahchua
    - sihugh

  channel:
    "#benchmarking"

  exclude_titles:
    - "[DO NOT MERGE]"
    - DO NOT MERGE
    - WIP

content-tools:
  members:
    - pmanrubia
    - ikennaokpala
    - chao-xian
    - mgrassotti
    - andrewgarner
    - alecgibson

  channel:
    "#content-tools"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - "Waiting on factcheck"
    - WIP

  use_labels: true

  exclude_labels:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - "Waiting on factcheck"

  quotes:
    - If it’s gonna take more than 30 minutes, or it needs deploying - write a card for it and chat to the Product Manager.
    - Try to pair when possible.
    - Be considerate to remote workers and follow the Working from home practices https://gov-uk.atlassian.net/wiki/x/Bz_5Bw and https://gov-uk.atlassian.net/wiki/display/CT/Working+from+home+ideas
    - Who's organising the next team lunch?
    - If you're not well, don't come in to the office. And get some rest!
    - Set your Slack status to away or do not disturb so people know whether they can disturb you.
    - Has your story got points?
    - Don't forget to assign your face to a card and PR if you're working on it or reviewing.
    - Don't forget the Jabra and fisheye lens if you're dialing in people!
    - If Hangouts is being flaky, try Slack calls or appear.in!

email:
  members:
    - davidbasalla
    - gpeng
    - rubenarakelyan
    - tuzz

  channel:
    "#email"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "[WIP]"

content-api:
  members:
    - kevindew
    - thomasleese
    - emmabeynon
    - steventux

  channel:
    "#content-api"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

taxonomy:
  members:
    - alextea
    - carvil
    - cbaines
    - koetsier
    - theKHutDeveloper
    - tijmenb
    - whoojemaflip

  channel:
    "#taxonomy"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - WIP
    - "[REVIEW ONLY]"
    - REVIEW ONLY
    - "[SEAL IGNORE]"

search-team:
  members:
    - MatMoore
    - brenetic
    - suzannehamilton
    - dwhenry
    - tatiana

  channel:
    "#search-team"

  quotes:
    - Biscuits
    - Respect each other
    - Document document document
    - Change when things don't work
    - Create a clear, shared vision of our goals
    - Work at a sustainable and accommodating pace
    - Make data driven decisions based on user needs
    - Make good use of people's time
    - Communicate priorities effectively across the whole team
    - Monitor progress against our goals
    - Celebrate progress
    - Unblock priority WIPs before starting new work

testing:
  members:
    - binaryberry
    - boffbowsh
    - fofr

  channel:
    "#testing"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

  quotes:
    - Everyone should have the opportunity to learn. Don’t be afraid to pick up stories on things you don’t understand and ask for help with them.
    - Be nice and respect each other. Support each other.
    - Don’t be a silo of knowledge

govuk-infrastructure:
  members:
    - deanwilson
    - surminus
    - afda16
    - SamLR
    - issyl0

  channel:
    "#govuk-infrastructure"

  exclude_titles:
    - "[DO NOT MERGE]"
    - WIP

  quotes:
    - ":eggplant:"
    - "indeed"
    - "naming is hard"
    - "If it's Wednesday, go to Beck's"
    - "We :heart: Taylor Swift"
    - "I like to pair, do you?"
    - "Sam has nice coffee"
    - "Go team!"
    - "Now that’s an interesting question"
    - "$integer = '34'"
    - "How hot is it? Probably 28"

servicemanual:
  members:
    - 36degrees
    - mcmillan

  channel:
    "#servicemanual"

  exclude_titles:
    - "[DO NOT MERGE]"
    - DO NOT MERGE
    - WIP

  exclude_repos:
    - govuk_elements
    - govuk_frontend_toolkit

  quotes:
    - ":wave:"

publishing-frontend:
  members:
    - nickcolley
    - miaallers
    - andysellick
    - vanitabarrett
    - fofr

  channel:
    "#publishing-frontend"

  exclude_titles:
    - "[DO NOT MERGE]"
