Developers:
  members:
    - bradwheel
    - ianyamey
    - j-clark
    - JustinTernullo
    - kellywu
    - PepperTeasdale
    - petrgazarov
    - elky

  channel:
    "#engineering"

  exclude_titles:
    - WIP
